name: "Easy release"
description: "Merge branches and publish release in one click"
inputs:
  source-branch:
    description: "Feature branch to be merged with target branch"
    default: "develop"
    required: true
  target-branch:
    description: "Branch to merge features from source branch"
    default: main
    required: true
  version:
    description: "Version tag for release vX.X.X"
    required: true
    default: "v0.0.0"
# secrets: inherit
runs:
  using: "node20"
  main: "dist/index.js"
