name: Easy merge
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Semantic release type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Easy merge
        id: easy-merge
        uses: arthurhovhannisyan31/easy-merge-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_branch: "develop"
          target_branch: "main"
          release_type: ${{ inputs.release_type }}
      - name: Log outputs
        run: |
          echo Released tag: ${{ steps.easy-merge.outputs.release_tag }}
      - name: Publish package
        uses: ./.github/actions/publish
        with:
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url: "https://npm.pkg.github.com"
