name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Semantic release type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  tag-validation:
    runs-on: ubuntu-latest
    name: Call release action
    steps:
      - uses: actions/checkout@v4
      - name: Easy release call
        id: easy-release
        uses: arthurhovhannisyan31/easy-release-action@v0.0.31
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_branch: "develop"
          target_branch: "main"
          release_type: ${{ inputs.release_type }}
