name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for release vX.X.X"
        required: true
        default: "v0.0.0"
jobs:
  tag-validation:
    runs-on: ubuntu-latest
    name: Call release action
    steps:
      - uses: actions/checkout@v4
      - name: Easy release call
        id: easy-release
        uses: arthurhovhannisyan31/easy-release-action@v0.0.15
        with:
          source-branch: "develop"
          target-branch: "main"
          version: ${{ inputs.version }}
          pat: ${{ secrets.GITHUB_TOKEN }}
